### ISSUE TITLE
HPM 'Repair' creating duplicate apps

### ISSUE THREAD

**Issue by quinnjudge** [ljbotero/hubitat-flair-vents#1]
When troubleshooting a discovery issue, I noticed that when a Hubitat Package Manager 'Repair' is run against the Flair entry, duplicate entries for the apps code are being generated.  I suspect there is some cleanup code missing for the app portion, as this does not seem to happen for the device code portion.

**Comment by ljbotero** [comment]
I believe this behavior is related to Hubitat Package Manager (HPM) rather than the app itself. This can happen if the app is installed manually first and then HPM is later used to install or manage the app, which can lead to duplicate entries.

To resolve this issue, I recommend using the "Match Up" feature in Hubitat Package Manager. This will allow HPM to recognize the manually installed app and link it correctly to the package, preventing duplication in the future.

Here’s how you can do it:
1. Open Hubitat Package Manager.
2. Select the "Match Up" option.
3. Follow the prompts to match your existing installation of the app to the HPM-managed package.

Once this is done, running a "Repair" in HPM should no longer generate duplicates.

I hope this helps resolve the issue! If you encounter any further problems, feel free to reach out here or in the community forums. For now, I'll close this issue as it doesn't appear to be related to the app code itself.
